//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ketabkhana.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Please enter Book Title"), MaxLength(50), MinLength(2)]
        public string bookTitle { get; set; }

        [Required(ErrorMessage = "Please enter Book Author's Name"), MaxLength(30), MinLength(2)]
        public string author { get; set; }

        [Required(ErrorMessage = "Please enter Book Puslisher's Name"), MaxLength(30), MinLength(2)]
        public string publisher { get; set; }

        [Required(ErrorMessage = "Please enter Book Edition"), MaxLength(10)]
        public string edition { get; set; }

        [Required, DataType(DataType.Currency)]
        public double price { get; set; }
        public int shopId { get; set; }

        [Required]
        public int quantity { get; set; }
        public string thumbnail { get; set; }
    
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
