//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ketabkhana.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Salary
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Please enter Username"), MaxLength(30), MinLength(4)]
        public string employeeUsername { get; set; }

        [Required(ErrorMessage = "Please enter salary"), DataType(DataType.Currency)]
        public double salary1 { get; set; }

        [Required(ErrorMessage = "Please enter bonus"), DataType(DataType.Currency)]
        public double bonus { get; set; }
    }
}
